---
- name: Playbook to migrate hosts to new Satellite
  hosts: all
  become: true
  tasks:
    - name: Unregister from old Satellite
      ansible.builtin.shell: subscription-manager unregister

    - name: Clean subscription data
      ansible.builtin.shell: subscription-manager Clean

    - name: Flush cache
      ansible.builtin.shell: rm -rf /var/cache/yum

    - name: Register to the new Satellite
      ansible.builtin.shell: |
        curl -sS --insecure 'https://up004580.bskyb.com/register?activation_keys=RHEL8-autopatched' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJpYXQiOjE2OTY4MzkyNDcsImp0aSI6IjYzYmQ3OWUzZDIxMmIxNTJjNDVkOWY0NTgzNTgzMWRmMTE5ZWYzY2YxZjAzZTY1NmRjM2E2NjAzMWJiZTRjZGUiLCJleHAiOjE2OTY4NTM2NDcsInNjb3BlIjoicmVnaXN0cmF0aW9uI2dsb2JhbCByZWdpc3RyYXRpb24jaG9zdCJ9.CPvva6lnWSQcHms9HSUKat2yWnnSUOeVhWsUVkL6cL4' | bash
