---
- name: Playbook to migrate hosts to new Satellite
  hosts: all
  become: true
  tasks:
    - name: Unregister from old Satellite
      ansible.builtin.shell: subscription-manager unregister
      ignore_errors: true

    - name: Clean subscription data
      ansible.builtin.shell: subscription-manager clean

    - name: Flush cache
      ansible.builtin.shell: rm -rf /var/cache/yum

    - name: Download Satellite certificate
      ansible.builtin.shell: |
        wget -P ~ http://up004580.bskyb.com/pub/katello-server-ca.crt
        wget -P ~ http://up004581.bskyb.com/pub/katello-server-ca.crt
        wget -P ~ http://up004582.bskyb.com/pub/katello-server-ca.crt

    - name: Remove katello old package
      ansible.builtin.shell:
        yum -y remove katello-ca-consumer-*

    - name: Download katello-customer rpm
      ansible.builtin.shell:
        yum -y install --nogpgcheck http://satellite.bskyb.com/pub/katello-ca-consumer-latest.noarch.rpm

    - name: Register the host
      ansible.builtin.shell:
        subscription-manager register --org "Sky" --activationkey "{{ sky_ak }}"
        